 "use client";
import {useEffect,useState} from "react";
import {AlertTriangle,ArrowRight,Bot,CheckCircle2,ChevronDown,Clock3,Factory,Gauge,PackageSearch,Route,ShieldCheck,Sparkles,Truck,XCircle} from "lucide-react";
import {scenarios,Scenario} from "@/data/scenarios";
import {Analysis} from "@/lib/agent";

export default function Dashboard(){
 const [scenarioId,setScenarioId]=useState("critical-delay");
 const [scenario,setScenario]=useState<Scenario>(scenarios[0]);
 const [analysis,setAnalysis]=useState<Analysis|null>(null);
 const [running,setRunning]=useState(false),[approved,setApproved]=useState(false);
 useEffect(()=>{setScenario(scenarios.find(s=>s.id===scenarioId)??scenarios[0]);setAnalysis(null);setApproved(false)},[scenarioId]);
 async function run(){setRunning(true);setApproved(false);try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenarioId})});const d=await r.json();setScenario(d.scenario);setAnalysis(d.analysis)}finally{setRunning(false)}}
 const cards=[
  ["Supplier",scenario.supplier.status,`${scenario.supplier.name} • ${scenario.supplier.delayDays}d delay`,Factory],
  ["Inventory",`${scenario.inventory.daysRemaining} days`,`${scenario.inventory.units.toLocaleString()} units available`,PackageSearch],
  ["Demand",scenario.demand.level,`${scenario.demand.dailyUnits.toLocaleString()} units/day`,Gauge],
  ["Logistics",scenario.logistics.status,`${scenario.logistics.delayDays}d inbound delay`,Truck]
 ];
 return <main className="min-h-screen grid-bg"><div className="mx-auto max-w-[1500px] px-5 py-6 md:px-8">
  <header className="mb-7 flex flex-col gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-5 md:flex-row md:items-center md:justify-between">
   <div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-400/10 p-2 text-cyan-300"><Bot/></div><div><h1 className="text-xl font-bold">Supply Chain AI Control Center</h1><p className="text-sm text-slate-400">Agentic disruption detection & response</p></div></div>
   <div className="flex flex-wrap gap-3"><label className="relative"><select value={scenarioId} onChange={e=>setScenarioId(e.target.value)} className="appearance-none rounded-xl border border-white/10 bg-slate-900 px-4 py-2.5 pr-10 text-sm">{scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-4 w-4"/></label>
   <button onClick={run} disabled={running} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 disabled:opacity-60"><Sparkles className="h-4 w-4"/>{running?"Agents Running...":"Run AI Investigation"}</button></div>
  </header>
  <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([t,v,s,I])=><div key={t as string} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="mb-5 flex justify-between text-sm text-slate-400">{t}<span className="text-cyan-300"><I/></span></div><div className="text-2xl font-bold">{v as string}</div><div className="mt-1 text-xs text-slate-500">{s as string}</div></div>)}</section>
  <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
   <div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-slate-500">Risk intelligence</p><h2 className="mt-2 text-3xl font-bold">{analysis?.risk??"READY"}</h2><p className="mt-1 text-sm text-slate-400">{analysis?"Analysis complete":"Run investigation to correlate signals"}</p></div><div className="rounded-xl border border-white/10 px-4 py-3 text-right"><p className="text-xs text-slate-500">Risk score</p><p className="text-2xl font-bold">{analysis?.riskScore??0}<span className="text-sm text-slate-500">/100</span></p></div></div>
   <div className="mt-7 h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400 transition-all duration-700" style={{width:`${analysis?.riskScore??0}%`}}/></div>
   <div className="mt-7 grid gap-3 md:grid-cols-2">{[["Supplier exposure",`${scenario.supplier.delayDays} days`],["Stock coverage",`${scenario.inventory.daysRemaining} days`],["Demand pressure",scenario.demand.level],["Inbound logistics",scenario.logistics.status]].map(([a,b])=><div key={a} className="flex justify-between rounded-xl border border-white/10 px-4 py-3 text-sm"><span className="text-slate-400">{a}</span><b>{b}</b></div>)}</div>
   {analysis&&<div className="mt-7 rounded-2xl border border-cyan-400/20 bg-cyan-400/[.04] p-5"><div className="flex gap-2 text-sm font-semibold text-cyan-300"><ShieldCheck className="h-4 w-4"/>Business impact</div><p className="mt-2 text-sm leading-6 text-slate-300">{analysis.impact}</p></div>}</div>
   <div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-slate-500">Agent activity</p><h2 className="mt-2 text-xl font-bold">Investigation timeline</h2></div><Clock3/></div><div className="mt-6 space-y-4">{analysis?analysis.steps.map((s,i)=><div key={s.agent} className="flex gap-3"><div className="flex flex-col items-center"><div className={`rounded-full p-2 ${s.status==="warning"?"bg-amber-400/10 text-amber-300":s.status==="recommendation"?"bg-cyan-400/10 text-cyan-300":"bg-emerald-400/10 text-emerald-300"}`}>{s.status==="warning"?<AlertTriangle className="h-4 w-4"/>:s.status==="recommendation"?<Sparkles className="h-4 w-4"/>:<CheckCircle2 className="h-4 w-4"/>}</div>{i<analysis.steps.length-1&&<div className="mt-1 h-7 w-px bg-white/10"/>}</div><div><p className="text-sm font-semibold">{s.agent}</p><p className="mt-1 text-xs leading-5 text-slate-500">{s.message}</p></div></div>):<div className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-500">Run the investigation to execute the multi-step agent workflow.</div>}</div></div>
  </section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
   <div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2"><Route className="text-cyan-300"/><h2 className="text-xl font-bold">Alternative suppliers</h2></div><p className="mt-1 text-sm text-slate-500">Delivery • cost • quantity • reliability</p><div className="mt-5 space-y-3">{scenario.alternatives.map(a=><div key={a.name} className={`rounded-xl border p-4 ${analysis?.recommendedSupplier===a.name?"border-cyan-400/40 bg-cyan-400/[.05]":"border-white/10"}`}><div className="flex justify-between"><div><b>{a.name}</b><p className="mt-1 text-xs text-slate-500">{a.quantity.toLocaleString()} units • {a.reliability}% reliability</p></div>{analysis?.recommendedSupplier===a.name&&<span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs text-cyan-300">Recommended</span>}</div><div className="mt-3 flex gap-4 text-xs text-slate-400">{a.deliveryDays} days <span>+{a.costIncrease}% cost</span></div></div>)}</div></div>
   <div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-2"><Sparkles className="text-cyan-300"/><h2 className="text-xl font-bold">Decision center</h2></div>{analysis?<><div className="mt-5 rounded-2xl border border-cyan-400/20 bg-cyan-400/[.04] p-5"><p className="text-xs uppercase tracking-[.18em] text-cyan-300">Next best action</p><p className="mt-3 text-lg font-semibold leading-7">{analysis.recommendation}</p></div><div className="mt-5"><p className="font-semibold">Agent reasoning</p><ul className="mt-3 space-y-2">{analysis.reasoning.map(x=><li key={x} className="flex gap-2 text-sm leading-6 text-slate-400"><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-cyan-300"/>{x}</li>)}</ul></div><div className="mt-6 flex gap-3"><button onClick={()=>setApproved(true)} disabled={approved} className="flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 text-sm font-bold text-slate-950 disabled:opacity-70"><CheckCircle2 className="h-4 w-4"/>{approved?"Action Approved":"Approve Action"}</button><button className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm"><XCircle className="h-4 w-4"/>Reject</button></div>{approved&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/[.05] px-4 py-3 text-sm text-emerald-300">Human approval recorded. Mitigation is ready for execution.</div>}</>:<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-7 text-sm text-slate-500">Decision Agent output will appear after investigation.</div>}</div>
  </section>
  <footer className="mt-7 border-t border-white/10 py-6 text-xs text-slate-600 flex justify-between"><span>AI Supply Chain Disruption Response Agent • Hackathon MVP</span><span>Human-in-the-loop • Simulated enterprise data</span></footer>
 </div></main>;
}
